### ISSUE TITLE
Wrapper shouldn't forward handled props to inner component

### ISSUE THREAD

**Issue by indeyets** [theadam/react-inform#15]
Currently, react-inform's Form:

1. [handles](https://github.com/theadam/react-inform/blob/master/src/form.js#L12-L16): `onChange`, `onValidate` and `value` fields
2. [forwards](https://github.com/theadam/react-inform/blob/master/src/form.js#L132-L134) all props to inner component

it probably shouldn't do (2)

**Comment by theadam** [comment]
Could you explain why it shouldn't do 2?  Without that, normal properties cannot be passed to your form.  

If `MyReactInform` is a wrapped form, and it expects an `onSubmit` property, this:
```
<MyReactInform onSubmit={...} />
```
wouldn't work unless the prop's passed to the wrapper weren't forwarded to the wrapped component.

**Comment by indeyets** [comment]
no-no… you misunderstood :)
it's ok to pass OTHER properties.

I'm talking strictly about those already handled by inform itself. The reasoning is mostly theoretical (oop black-box)

```
const propsToForward = { ...this.props };
delete props.ToForward.onChange;
delete props.ToForward.onValidate;
delete props.ToForward.value;
…
```

**Comment by indeyets** [comment]
practical reason: I just saw a developer who tried to attach this `onChange` to the `<form>` of internal component :-(

**Comment by theadam** [comment]
ah, I see.  This makes more sense :) Yeah I think thats valid.  I don't see a reason that the inner component would ever need those.

**Comment by theadam** [comment]
#16 should take care of it.  Let me know if that works for you.  I won't be releasing immediately, as there are a few more changes I want in there.
