### ISSUE TITLE
Problem creating form without using field/validate keys

### ISSUE THREAD

**Issue by kristiankeane** [theadam/react-inform#21]
I'm trying to create a dynamic form using your recent example, however an error is thrown when using the decorator or function without the field/validate keys. It kind of looks like the packaged/babelified code messed up/discarded the default params:

```
// from src form.js
export default function form({
  fields: defaultFields = [],
  validate: defaultValidate = () => ({}),
} = {}) {
  return (Wrapped) => class FormWrapper extends Component {

// from lib form.js
function form(_ref) {
  var fields = _ref.fields;
  var _ref$validate = _ref.validate;
  var validate = _ref$validate === undefined ? function () {
    return {};
  } : _ref$validate;

  return function (Wrapped) {
```

If I import react-inform/lib/form.js and change 
```
var fields = _ref.fields; 
to 
var fields = (_ref && _ref.fields) || [];
```
that error is fixed, but another error is thrown for the validate var of course.

Is this a babelification issue, or am I missing something here? Please let me know if you need any more details, and thanks for the great form library!

**Comment by kristiankeane** [comment]
@theadam Ah, that's the problem. Thanks.

**Comment by theadam** [comment]
@kristiankeane The new version has been released

**Comment by kristiankeane** [comment]
@theadam Awesome! That was quick!
