### ISSUE TITLE
Validate on submit

### ISSUE THREAD

**Issue by adiospace** [theadam/react-inform#28]
Hi Adam, thank you for the library. Simple stuff, no fuss. 

Do you think is possible to add a flag, `blurTouch={Bool} default: true`, to control the blur validation? I only want to validate on submit, and that will do it.

P.S. I actually had to fork and add the flag myself but if you're ok with it, I can make a PR.

Update: No, that will not do it. It's more complex than that it seems. Everything is happening real time, on change, what I need is to validate at submit (not on change or on blur, or on componentWillReceiveProps). So I have to change quite a bit of code for this to happen.

**Comment by theadam** [comment]
@adiospace Sorry for the delay in my response.  Could you possibly used the `touched` prop for this?  Basically always have it be set to false for every field, then when an invalid submit is attempted, set them all to true?

something like: https://www.webpackbin.com/bins/-Kjn9tXOTUhm540cKrTC

**Comment by adiospace** [comment]
No worries, I actually ended up doing something pretty similar. 👍
