### ISSUE TITLE
Boolean values for checkboxes are not being well handled

### ISSUE THREAD

**Issue by facuspagnuolo** [theadam/react-inform#34]
## TL;DR;
If you initialize a form including a boolean field, if that field is initialized as `false`, the value you will get from react-inform is an empty string. 

## Example
```js
import React from  'react'
import { form, createValidate } from 'react-inform'

class Form extends React.Component {
  constructor() {
    super()
    this.state = { values: { boolean: false, ... } }
  }

  componentWillMount() {
    this.props.form.onValues(this.state.values)
  }

  render() {
    console.log(this.props.fields.boolean.value)
    return <p>{this.props.fields.boolean.value}</p>
  }
}
export default form({ fields: ['boolean'], validate: {} })(Form)
```

## Solution
Debugging I found the [following](https://github.com/theadam/react-inform/blob/master/src/form.js#L145), that I think it may be the problem since you are doing `false || ''` which will return `''`. Maybe you can change the way you are handling booleans there.

Thanks!

**Comment by theadam** [comment]
@facuspagnuolo Good catch, Maybe we should explicitly check for `undefined` there.  Would that be your suggestion?

**Comment by facuspagnuolo** [comment]
Maybe, but actually I think that there may be no need for handling `undefined`, `null` or `false` values, I mean, why not just assigning the current value? Is there any reason why avoiding `undefined` or `null` values?

**Comment by theadam** [comment]
@facuspagnuolo I know the reason its set to something other than `undefined` is to avoid the warning in (this example)[https://codesandbox.io/s/oxzvmoov09], but it looks like null is acceptable.  Seems like the solution might be to convert `undefined` values to `null` here, and accept anything else?

**Comment by facuspagnuolo** [comment]
@theadam I see, yes, that's a good idea :)

**Comment by theadam** [comment]
@facuspagnuolo 0.2.4 is released with this fix!
