### ISSUE TITLE
Reset Values Programmatically

### ISSUE THREAD

**Issue by reyhansofian** [theadam/react-inform#37]
Hi, thanks for your great package! Can we reset all field's value programmatically without using `ResetFormButton`? also I noticed that by using `ResetFormButton` will show up the error

**Comment by theadam** [comment]
You can use the `form` prop passed to your component to do this if you are inside the wrapped component.  Use `props.form.onValues({})` to reset the values and `props.form.resetTouched()` to reset all your inputs to their state before the errors were shown.  

If you are using the component as a controlled component (passing all of the props down to the wrapped component from a parent).  You can similarly use the `touched` and `value` props.
