### ISSUE TITLE
Dynamic Forms

### ISSUE THREAD

**Issue by enyachoke** [theadam/react-inform#4]
We are currently working https://github.com/AMPATH/ng-amrs which has a data collection bit with some quite lengthy forms defined in json. We use http://angular-formly.com/ to render the forms and we basically go through a json form and create a formly config. We are looking at alternatives and react has been thrown on the table. The reason am looking at inform is the way it handles forms it means we can simply create a field map and have it rendered. But they are cases we have to deal with fields added at runtime which also contain validations. Can inform handle this cases well. Another thing is that our forms have pages but I think we can figure out that. The only thing I need to understand is how to add validations and adding fields at runtime. Some of the validations are also functions but I think inform can handle that.

**Comment by theadam** [comment]
RIght now fields cannot be added at runtime, I will add this functionality as soon as possible.
