### ISSUE TITLE
Transfer input value from the outside

### ISSUE THREAD

**Issue by Oopscurity** [theadam/react-inform#8]
Hello,
It looks like there's no opportunity to set the fields' value anywhere expect direct keyboard input events.
Is it possible to add support of transferring `value` to the fields from the outside (for example, by API like `setValue()`?

**Comment by theadam** [comment]
Depends on where this is happening, but within the form component gets passed a `form` property that has an `onValues()` function.  You could use that to set all of the values.  I will try to mock up an example as soon as possible.

**Comment by Oopscurity** [comment]
@theadam Thank you for the response.
I missed `form.onValues()` in the documentation. This method actually does exactly what we need.

**Comment by theadam** [comment]
Great! Closing!
