### ISSUE TITLE
Call wrapped form's methods from outside

### ISSUE THREAD

**Issue by Oopscurity** [theadam/react-inform#9]
Hello,
Do I have any way to call wrapped form's methods? The wrapper has `fields` and `errors` properties but it looks like I don't have real access to the wrapped form.

In addition, it can be awesome to add an opportunity to force validate the form *remotely*.

**Comment by theadam** [comment]
Are you attempting to use refs to get access to the form?  Is this what you mean by from the outside?

**Comment by Oopscurity** [comment]
@theadam Yes, I try to manage the form with refs. For example, I have
```javascript
<WrappedForm ref={c => this.form = c} />
```
And then I call `this.form.method()`.

**Comment by theadam** [comment]
I am not sure I want to put too much effort into an API to be used with a reference to a form at the moment.  However, if you are using the latest version, you should be able to either use `this.form.formProps().forceValidate()` or `this.form.touch(fieldNameArray)`.  The second will force every field name in the array to start passing errors down.  Let me know if this works.

**Comment by Oopscurity** [comment]
Thank you, @theadam! I have tried the first way (`this.form.formProps()`), so it works and returns forms utility functions (https://github.com/theadam/react-inform#form). I think you should add a tip to docs that if user needs to get access to that functions, he has to call `this.form.formProps()`. There's no information about it anywhere :)

**Comment by theadam** [comment]
Good @Oopscurity.  Id like to think of a different way to provide this functionality from the outside.  I personally try to avoid refs as much as possible, as it breaks the declarative nature of the view.  My instinct would be to allow that property to be controlled with passed props, but it feels clunky to me.  If I do not think of another approach, I might end up documenting this.  Just beware, the api might change in future versions!  Glad it worked!
